# Generated by Django 3.1.6 on 2021-11-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['UserName', 'UserPassword']},
        ),
    ]
