# Generated by Django 4.0.1 on 2022-02-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='av',
            new_name='au',
        ),
        migrations.RenameField(
            model_name='prenatal',
            old_name='dom',
            new_name='don',
        ),
    ]
