# Generated by Django 4.0.1 on 2022-02-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_av_appointment_au_rename_dom_prenatal_don'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=200)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.appointment')),
            ],
        ),
    ]
