# Generated by Django 3.1.6 on 2021-11-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20211116_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['UserName']},
        ),
    ]
