# Generated by Django 4.0.1 on 2022-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_addendum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='gestational_age_last_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gestational_age_ultrasound',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cd',
            field=models.CharField(max_length=500),
        ),
    ]
