# Generated by Django 4.0.1 on 2022-02-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_remove_appointment_gestational_age_last_menstrual_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasoundExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig', models.CharField(max_length=100)),
                ('pfe', models.CharField(max_length=200)),
                ('la', models.CharField(max_length=200)),
                ('placenta', models.CharField(max_length=200)),
                ('other_info', models.CharField(max_length=600)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.medicalexam')),
            ],
        ),
    ]
